[package]
name = "UnifiedCompute"
version = "1.0.0"

[addresses]
# Replace 0x... with your actual Testnet account address
UnifiedCompute = "0xd144f994fb413c68308e64805774d17ec9703cb4e125dfe19e655ffe209d18b4"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-stdlib"

